# Generated by Django 3.2 on 2021-04-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210421_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Iamge',
            field=models.URLField(max_length=5000),
        ),
    ]
